name: Deploy to Server

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build Docker image
    - name: Build Docker image
      run: docker build -t anvar-app .

    # Deploy to server using SSH with password
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 100.42.181.66
        username: root # or replace with your user
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop anvar-app || true
          docker rm anvar-app || true
          docker run -d --name anvar-app -p 8010:8000 anvar-app
